server:
  port: 8080

spring:
  application:
    name: demo-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    one:
      url: http://127.0.0.1:8081
    two:
      url: http://127.0.0.1:8082

logging:
  level:
    org.springframework.cloud: DEBUG